version: '3.3'

services:

  base:
    networks:
      - brain_storm-network
    volumes:
      - my-storage:/usr/src/brain_storm
    build:
      dockerfile: ./brain_storm/Dockerfile
      context: .
    image: brain_storm-base:latest

  data_base:
    image: mongo
    volumes:
      - my-storage:/usr/src/brain_storm
    networks:
      - brain_storm-network
    ports:
      - '27017:27017'


  message_queue:
    image: rabbitmq
    networks:
      - brain_storm-network
    ports:
      - '5672:5672'
    healthcheck:
      test: ["CMD", "curl", "-f","http://0.0.0.0:5672"]
      interval: 30s
      timeout: 10s
      retries: 10

  api:
    build:
      dockerfile: ./brain_storm/api/Dockerfile
      context: .
    volumes:
      - my-storage:/usr/src/brain_storm
    networks:
      - brain_storm-network
    ports:
      - 5000:5000
    depends_on:
      - data_base
      - base
    restart: on-failure

  server:
    build:
      dockerfile: ./brain_storm/server/Dockerfile
      context: .
    volumes:
      - my-storage:/usr/src/brain_storm
    networks:
      - brain_storm-network
    ports:
      - 8000:8000
    depends_on:
      - message_queue
      - base
    restart: on-failure

  parser_color:
    build:
      dockerfile: ./brain_storm/parsers/Dockerfile
      context: .
    volumes:
      - my-storage:/usr/src/brain_storm
    networks:
      - brain_storm-network
    depends_on:
      - message_queue
      - base
    enviroment:
      - PARSER: color_image
    restart: on-failure

  parser_depth:
    build:
      dockerfile: ./brain_storm/parsers/Dockerfile
      context: .
    volumes:
      - my-storage:/usr/src/brain_storm
    networks:
      - brain_storm-network
    depends_on:
      - message_queue
      - base
    enviroment:
      - PARSER: depth_image
    restart: on-failure

  parser_pose:
    build:
      dockerfile: ./brain_storm/parsers/Dockerfile
      context: .
    volumes:
      - my-storage:/usr/src/brain_storm
    networks:
      - brain_storm-network
    depends_on:
      - message_queue
      - base
    enviroment:
      - PARSER: pose
    restart: on-failure


  parser_feelings:
    build:
      dockerfile: ./brain_storm/parsers/Dockerfile
      context: .
    volumes:
      - my-storage:/usr/src/brain_storm
    networks:
      - brain_storm-network
    depends_on:
      - message_queue
      - base
    enviroment:
      - PARSER: feelings
    restart: on-failure


  saver:
    build:
      dockerfile: ./brain_storm/saver/Dockerfile
      context: .
    volumes:
      - my-storage:/usr/src/brain_storm
    networks:
      - brain_storm-network
    depends_on:
      - message_queue
      - data_base
      - base
    restart: on-failure

networks:
  brain_storm-network:

volumes:
  my-storage: